/***************************************************************************
*
*  Programmers and Purdue Email Addresses:
*  1. ozubi@purdue.edu
*  2. mtolkacz@purdue.edu
*  3. elkins15@purdue.edu (delete line if no third partner)
*
*  Lab #: lab08
*
*  Academic Integrity Statement:
*
*  We have not used source code obtained from any other unauthorized source,
*  either modified or unmodified.  Neither have we provided access to our code
*  to another. The project we are submitting is our own original work.
*
*  Day, Time, Location of Lab: Tuesday, 3:30, SC 289
*
*  Program Description: This program displays the games won for a random\
*  generated game of roulette!
*
***************************************************************************/
#include <math.h>
#include <stdlib.h>
#include <stdio.h>

int getValue(int);
void printOutput(int,int);

char getOutcomeColor(int);
char getOutcomeType(int);
char getOutcomePlace(int);
int getOutcomeDozen(int);

int main(void)
{
//Local Declarations
  int seedValue; //The random generated value created by the seed
  int spins; //The number of spins entered by the user
  int seed; //The seed value entered by the user

//Statements
  printf("Enter the starting seed -> ");
  scanf("%d",&seed);
  printf("Enter the number of winning spins -> ");
  scanf("%d",&spins);

//Function Calls
  while (spins > 0)
  {
    seedValue = getValue(seed);
    if (seedValue != 0)
    {
      printOutput(seed, seedValue);
      --spins;
    }
    seed++;
  }

//Spacing
  printf("\n");

//Return Statement
  return (0);
} //End main

/***************************************************************************
*
*  Function Information
*
*  Name of Function: getValue
*
*  Function Return Type: int
*
*  Parameters (list data type, name, and comment one per line):
*    1. int, seed, The seed value entered by the user
*
*  Function Description: This function generates a random value with a given seed.
*
***************************************************************************/
int getValue(int seed)
{
//Local Declarations
  int value; //To store the random value generated by the given seed

//Statements
  srand(seed);
  value = rand() % 37;

//Return Staetment
  return (value);
}

/***************************************************************************
*
*  Function Information
*
*  Name of Function: printOutput
*
*  Function Return Type: void
*
*  Parameters (list data type, name, and comment one per line):
*    1. int, seed, the value of the seed generated from the random number function
*    2. int, seedValue, the value of the seed entered by the user 
*
*  Function Description: This function prints the output of the games won for the user
*
***************************************************************************/
void printOutput(int seed, int seedValue)
{
//Local Declarations
  char outcomeColor; //Outcome of game color (Black, Red)
  char outcomeType; //Outcome of game type (Even, Odd)
  char outcomePlace; //Outcome of game place (Lower, Upper)
  int outcomeDozen; //Outcome of game dozen (First dozen, Second Dozen, third Dozen)

//Statements
  outcomeColor = getOutcomeColor(seedValue);
  outcomeType = getOutcomeType(seedValue);
  outcomePlace = getOutcomePlace(seedValue);
  outcomeDozen = getOutcomeDozen(seedValue);

//Output Statements
  printf("\nSeed #: %d", seed);
  printf("\nBall Landing: %d", seedValue);
  printf("\nWinning Games: %c %c %c %d", outcomeColor, outcomeType, outcomePlace, outcomeDozen);
  printf("\n-=-=-=-=-=-=-=-=-=-=-=-=-=-");

//Return Statement
  return;
} //End printOutput

/***************************************************************************
*
*  Function Information
*
*  Name of Function: getOutcomeColor
*
*  Function Return Type: char
*
*  Parameters (list data type, name, and comment one per line):
*    1. int, value, the value of the game won by the user
*
*  Function Description: This function tests for the game colo (red or black)
*
***************************************************************************/
char getOutcomeColor(int value)
{
//Local Declarations
  char outcome; //Outcome of the color of the game

//Chec for Red
  switch(value)
  {
    case 1:
      outcome = (char) 'R';
      break;
    case 3:
      outcome = (char) 'R';
      break;
    case 5:
      outcome = (char) 'R';
      break;
    case 7:
      outcome = (char) 'R';
      break;
    case 9:
      outcome = (char) 'R';
      break;
    case 12:
      outcome = (char) 'R';
      break;
    case 14:
      outcome = (char) 'R';
      break;
    case 16:
      outcome = (char) 'R';
      break;
    case 18:
      outcome = (char) 'R';
      break;
    case 19:
      outcome = (char) 'R';
      break;
    case 21: 
      outcome = (char) 'R';
      break;
    case 23:
      outcome = (char) 'R';
      break;
    case 25:
      outcome = (char) 'R';
      break;
    case 27:      
      outcome = (char) 'R';
      break;
    case 30:
      outcome = (char) 'R';
      break;
    case 32:
      outcome = (char) 'R';
      break;
    case 34:
      outcome = (char) 'R';
      break;
    case 36:
      outcome = (char) 'R';
      break;
    default:
      outcome = (char) 'B';
  }
//Return Statement      
  return (outcome);
} //End getOutcomeColor

/***************************************************************************
*
*  Function Information
*
*  Name of Function: getOutcomeType
*
*  Function Return Type: char
*
*  Parameters (list data type, name, and comment one per line):
*    1. int, value, the value of the game won by the user
*
*  Function Description: This program checks if the game was an even or an odd
*  number. 
*
***************************************************************************/
char getOutcomeType(int value)
{
//Local Declarations
  char outcome; //Outcome of the game type (even, odd)

//Check for even
  if (value % 2 == 0)
  {
    outcome = (char) 'E';
  }
  else
  {
    outcome = (char) 'O';
  }

//Return Statment
  return(outcome);
} //End getOutcomeType

/***************************************************************************
*
*  Function Information
*
*  Name of Function: getOutcomePlace
*
*  Function Return Type: char
*
*  Parameters (list data type, name, and comment one per line):
*    1. int, value, the value of the game won by the user
*
*  Function Description: This function checks if the game won is part of the 
*  lower half or upper half.
*
***************************************************************************/
char getOutcomePlace (int value)
{
//Local Declarations
  char outcome; //Outcome of game place (lower, upper)

//Check for lower half
  if (value <= 18)
  {
    outcome = (char) 'L';
  }
  else
  {
    outcome = (char) 'H';
  }

//Return Statment
  return(outcome);
} //End getOutcoemPlace

/***************************************************************************
*
*  Function Information
*
*  Name of Function: getOutcomeDozen
*
*  Function Return Type: int
*
*  Parameters (list data type, name, and comment one per line):
*    1. int, value, the game value won by the user
*
*  Function Description: This function checks which dozen the game won is within.
*
***************************************************************************/
int getOutcomeDozen (int value)
{
//Statement
  value--;
  value /= 12;
  value++;

//Return Statement
  return(value);
} //End getOutcomeDozen
